# Generated by Django 2.2 on 2023-11-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
