# Generated by Django 2.2 on 2023-11-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
