# Generated by Django 2.2 on 2023-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20231104_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='', verbose_name='Link hình ảnh'),
        ),
    ]
